### PR TITLE
update all deps of magicbook-codesplit to latest

### PR DESCRIPTION
**Pull request by joeyklee**
Hi @runemadsen,

Apologies for the added work/efforts here. I realized that updating the through2 dependency was not enough, but rather we needed to update the other packages as well.

I will make additional PRs for the magicbook-codesplit and magicbook-katex shortly with all updated package dependencies as well.

My mistake for not catching this earlier. I think this should resolve the build issues we've been encountering in nature-of-code/noc-book#158

### CODE REVIEW

**Comment by shiffman** [comment]
@runemadsen I have admin privileges on the magic book, would you prefer to review everything or is it helpful if @joeyklee and I review together minor things like this and I will go ahead and merge?

**Comment by runemadsen** [comment]
I was just about to say that: You should totally go ahead and merge these things. I can also add you to the NPM package, so you can run `npm run publish` to release new versions.

My only ask is that you run `npm run test` before every release to make sure that it didn't break anything. :)

**Comment by joeyklee** [comment]
@runemadsen - super! thanks so much! I'm happy to support this in any way that I can + will make sure the tests pass before creating a new release. 🙏

**Comment by shiffman** [comment]
Ok, merging!

**Comment by joeyklee** [comment]
@shiffman - thanks! We should also merge in this one - https://github.com/magicbookproject/magicbook/pull/23 - and publish to npm as well :) Thank you!

**Pull request merged**
